// Bundle the TypeScript supervisor module to a single, tree-shaken ESM file that
// the raw-JS c8ctl-plugin.js can `await import('./supervisor.dist.js')`.
//
// Effect is *bundled in* (not shipped as a raw ~51 MB dependency): tree-shaking
// the actual supervisor surface drags in only the handful of Effect modules we
// use, and drops `msgpackr` (native addon) + `fast-check` entirely — they are
// never imported by this surface. The measured shipped cost is ~100 KB, not 51 MB.
import { build } from "esbuild";
import { readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const outfile = join(repoRoot, "supervisor.dist.js");

const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
const effectVersion = pkg.devDependencies?.effect ?? pkg.dependencies?.effect ?? "unknown";

await build({
  entryPoints: [join(here, "src/index.ts")],
  outfile,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22",
  // Effect IS bundled + tree-shaken (that is the whole point — do NOT externalize it).
  treeShaking: true,
  minify: true,
  // Preserve upstream (Effect, MIT) license/copyright banners in the bundled
  // artifact so the published supervisor.dist.js stays license-compliant.
  legalComments: "eof",
  banner: {
    js: `// GENERATED by supervisor/build.mjs — do not edit. Source: supervisor/src/*.ts (effect@${effectVersion} tree-shaken in).`,
  },
});

const { size } = statSync(outfile);
console.log(`supervisor.dist.js built: ${(size / 1024).toFixed(1)} KB (effect@${effectVersion} bundled + tree-shaken)`);
